export const COLORS = {
  lime: "bg-lime-600",
  cyan: "bg-cyan-400",
  rose: "bg-rose-600",
  purple: "bg-purple-600",
  white: "bg-white",
};

export const COLOR_SEQUENCE = [
  COLORS.lime,
  COLORS.cyan,
  COLORS.rose,
  COLORS.purple,
];

export const CORNER_INDICES = {
  1: "common",
  2: "common",
  3: "common",
  4: "common",
  5: "top_right",
  6: "top_right",
  7: "top_right",
  8: "top_right",
  9: "common",
  10: "common",
  11: "top_right",
  12: "common",
  13: "common",
  14: "top_right",
  15: "common",
  16: "common",
  17: "top_right",
  18: "common",
  19: "common",
  20: "top_left",
  21: "common",
  22: "common",
  23: "common",
  24: "common",
  28: "common",
  29: "common",
  30: "common",
  31: "bottom_right",
  32: "common",
  33: "common",
  34: "common",
  35: "top_left",
  36: "top_left",
  37: "top_left",
  38: "top_left",
  39: "top_left",
  43: "bottom_right",
  44: "bottom_right",
  45: "bottom_right",
  46: "bottom_right",
  47: "bottom_right",
  48: "common",
  49: "common",
  50: "common",
  51: "top_left",
  52: "common",
  53: "common",
  54: "common",
  58: "common",
  59: "common",
  60: "common",
  61: "common",
  62: "bottom_right",
  63: "common",
  64: "common",
  65: "bottom_left",
  66: "common",
  67: "common",
  68: "bottom_left",
  69: "common",
  70: "common",
  71: "bottom_left",
  72: "common",
  73: "common",
  74: "bottom_left",
  75: "bottom_left",
  76: "bottom_left",
  77: "bottom_left",
  78: "common",
  79: "common",
  80: "common",
  81: "common",
};
